@startmindmap img_proc_basic_08
+ シーンの復元
-- 8-1 画像と空間の幾何学的関係と3次元復元
--- 8-1-1 画像上の位置と空間の位置
--- 8-1-2 ステレオビジョン
--- 8-1-3 アクティブステレオ
--- 8-1-4 未知のカメラを用いた3次元復元
++ 8-2 光学的なシーン復元
+++ 8-2-1 インバースレンダリング
+++ 8-2-2 反射特性
+++ 8-2-3 反射成分の分離
+++ 8-2-4 形状の復元
+++ 8-2-5 反射特性の復元
+++ 8-2-6 照明環境の復元
@endmindmap
