@startmindmap img_proc_expert_06
+ 周波数領域におけるフィルタリング
-- 6-1 画像のフーリエ変換
--- 6-1-1 2次元フーリエ変換
--- 6-1-2 画像のフーリエ変換
-- 6-2 周波数フィルタリング
--- 6-2-1 周波数フィルタリング
--- 6-2-2 空間フィルタリングと周波数フィルタリングの関係
++ 6-3 ローパスフィルタ、ハイパスフィルタ、バンドパスフィルタ
+++ 6-3-1 ローパスフィルタ
+++ 6-3-2 空間フィルタリングによる平滑化との関係
+++ 6-3-3 ハイパスフィルタ
+++ 6-3-4 バンドパスフィルタ
++ 6-4 高域強調フィルタ
+++ 6-4-1 高域強調フィルタ
+++ 6-4-2 空間フィルタリングによる鮮鋭化との関係
@endmindmap
