@startmindmap img_proc_expert_Appendix
+ Appendix
-- a-1 画像処理の歴史
--- a-1-1 
--- a-1-2 
--- a-1-3 
--- a-1-4 
--- a-1-5 
-- a-2 数学的基礎
--- a-2-1 
--- a-2-2 
--- a-2-3 
--- a-2-4 
--- a-2-5 
-- a-3 画像入力
--- a-3-1 
--- a-3-2 
--- a-3-3 
--- a-3-4 
--- a-3-5 
++ a-4 画像出力
+++ a-4-1 
+++ a-4-2 
+++ a-4-3 
+++ a-4-4 
++ a-5 画像処理の特性測定
++ a-6 規格
+++ a-6-1 
+++ a-6-2 
+++ a-6-3 
+++ a-6-4 
++ a-7 知的財産権
+++ a-7-1 
+++ a-7-2 
@endmindmap
