@startmindmap img_proc_expert_13
+ 深層学習による画像認識と生成
-- 13-1 ニューラルネットワーク
--- 13-1-1 
--- 13-1-2 
-- 13-2 深層学習
--- 13-2-1 
--- 13-2-2 
++ 13-3 CNNによる画像認識と画像生成
+++ 13-3-1 
+++ 13-3-2 
+++ 13-3-3 
+++ 13-3-4 
+++ 13-3-5 
+++ 13-3-6 
@endmindmap
