@startmindmap img_proc_basic_03
+ レンダリング

-- 3-1 レンダリングの処理過程
--- 透視投影
--- 陰面消去・ラスタ化
--- シェーディング
--- 効果付加

-- 3-2 陰面消去
--- バックフェースカリング
---- 陰面消去
---- 陰線消去
--- 奥行きソート法
---- ペインタアルゴリズム
--- スキャンライン法
---- スキャンライン（走査線）
---- コヒーレンス
--- Zバッファ法
---- Zバッファ
---- フレームバッファ
--- レイトレーシング法（光線追跡法）
---- バウンディングボリューム

-- 3-3 シェーディング
--- シェーディング
---- シェーディング
---- 影付け（シャドウイング）
--- 要素
---- 光源
----- 平行光線
----- 点光源
----- 線光源
----- 面光源
---- 光
----- 直接光
----- 間接光
---- 物体からの光
----- 反射光
----- 透過光
----- 散乱光
--- シェーディングモデル
--- 環境光
--- 拡散反射
---- 平行光線
----- 入射角余弦の法則
---- 点光源
----- 逆二乗の法則
--- 鏡面反射
---- ハイライト
---- フォンのモデル
---- ブリンのモデル
---- クック・トランスのモデル
---- 双方向反射率分布関数（BRDF: Bidirectional Reflectance Distribution Function）
--- 3-3-7 完全鏡面反射・透過・屈折
---- スネルの法則
--- 3-3-8 散乱・減衰現象の表示
---- レイマーチング法
--- 3-3-9 スムーズシェーディング
---- コンスタントシェーディング
---- スムーズシェーディング
----- グローシェーディング
----- フォンシェーディング

-- 3-4 影付け
--- 3-4-1 本影と半影
--- 3-4-2 影の計算法
++ 3-5 マッピング
+++ 3-5-1 マッピングの概要
+++ 3-5-2 テクスチャマッピング
+++ 3-5-3 バンプマッピング
+++ 3-5-4 環境マッピング
+++ 3-5-5 ソリッドテクスチャマッピング
++ 3-6 イメージベーストレンダリング
+++ 3-6-1 イメージペーストレンダリングの概要
+++ 3-6-2 テクスチャマッピングアプローチ
+++ 3-6-3 画像再投影アプローチ
+++ 3-6-4 パノラマ画像アプローチ
+++ 3-6-5 ビューモーフィングアプローチ
+++ 3-6-6 レイデータベースアプローチ
+++ 3-6-7 イメージペーストライティング
++ 3-7 大域照明計算
+++ 3-7-1 ラジオシティ法
+++ 3-7-2 フォトンマッピング法
++ 3-8 ボリュームレンダリング
+++ 3-8-1 ボリュームビジュアライゼーション
+++ 3-8-2 ボリュームレンダリング
++ 3-9 ノンフォトリアリスティックレンダリング
+++ 3-9-1 NPRの概要と特徴
+++ 3-9-2 2次元画像を入力とするNPR
+++ 3-9-3 3次元画像を入力とするNPR
@endmindmap