@startmindmap img_proc_expert_12
+ パターン認識
-- 12-1 パターン認識の基本的なアプローチ
--- 12-1-1 
--- 12-1-2 
--- 12-1-3 
--- 12-1-4 
--- 12-1-5 
--- 12-1-6 
--- 12-1-7 
--- 12-1-8 
--- 12-1-9 
-- 12-2 領域学習の概要
--- 12-2-1 
--- 12-2-2 
++ 12-3 教師なし学習とクラスタリング
+++ 12-3-1 
+++ 12-3-2 
++ 12-4 教師あり学習
+++ 12-4-1 
+++ 12-4-2 
+++ 12-4-3 
++ 12-5 機械学習による画像認識の応用例
+++ 12-5-1 
+++ 12-5-2 
+++ 12-5-3 
@endmindmap
