@startmindmap img_proc_expert_10
+ 領域処理
-- 10-1 領域処理のための特徴量
--- 10-1-1 領域のテクスチャ
--- 10-1-2 2次元フーリエ変換による周波数特徴量
--- 10-1-3 ガボールフィルタによる局所周波数特徴量
--- 10-1-4 同時生起行列を用いた統計的特徴量
++ 10-2 領域分割処理
+++ 10-2-1 領域分割処理のアプローチ
+++ 10-2-2 隣接画素の階層的な統合による領域分割処理
+++ 10-2-3 画素特徴量のパラメータ空間でのクラス分けによる領域分割処理
+++ 10-2-4 画素特徴量を効率よくクラス分けするミーンシフト
+++ 10-2-5 対象物と背景の間のエッジを利用した領域分割処理
+++ 10-2-6 グラフカットを用いた領域分割処理
@endmindmap
