@startmindmap img_proc_expert_11
+ パターン・図形・特徴の検出とマッチング
-- 11-1 テンプレートマッチングによるパターンの検出
--- 11-1-1 テンプレートマッチング
--- 11-1-2 類似度
--- 11-1-3 サブピクセル位置推定
--- 11-1-4 高速探索法
--- 11-1-5 参照画素の選択による高速化
-- 11-2 エッジ検出とヒストグラムによるパターン検出
--- 11-2-1 エッジ情報を用いたチャンファーマッチング
--- 11-2-2 ヒストグラム情報を用いたアクティブ探索
-- 11-3 特徴点検出
--- 11-3-1 コーナー検出
--- 11-3-2 DoG画像を用いた特徴点とスケールの検出
++ 11-4 特徴点の記述とマッチング
+++ 11-4-1 スケールと回転に不変な特徴記述（SIFT）
+++ 11-4-2 2値特徴量
+++ 11-4-3 対応点マッチング
++ 11-5 図形要素検出
+++ 11-5-1 ハフ変換
+++ 11-5-2 一般化ハフ変換
+++ 11-5-3 ランダム化ハフ変換
++ 11-6 顕著性マップ
+++ 11-6-1 特徴統合理論
+++ 11-6-2 顕著性マップ
@endmindmap
