@startmindmap img_proc_basic_02
+ モデリング

-- 2-1 形状モデル
--- ワイヤーフレームモデル
--- サーフェスモデル
--- ソリッドモデル
--- 表示

-- 2-2 ソリッドモデル
--- CSG表現
---- Constructive Solid Geometry、空間領域構成法
--- 境界表現
---- 基本要素
----- 頂点
----- 稜線
----- 面
---- 位相
---- 幾何
---- オイラー操作
----- MEV（Make Edge Vertex）
----- MEF（Make Edge Face）
----- KEV（Kill Edge Vertex）
--- スイープ表現
---- 軌道と軌跡

++ 2-3 曲線・曲面
+++ 曲線の表現
++++ 代数曲線
+++++ 陽関数
+++++ 隠関数
++++ パラメータ（媒介変数）
+++ 2次曲線（円錐曲線）
++++ 楕円
++++ 放物線
++++ 双曲線
+++ パラメトリック曲線
++++ ベジエ曲線
+++++ 制御点
+++++ 凸包性
+++++ 細分割法
++++ Bスプライン曲線
+++ パラメトリック曲面
++++ ベジエ曲面
++++ Bスプライン曲面
+++ レンダリングにおける曲面の扱い
++++ 曲面表現のままで処理
++++ 小さなポリゴンで近似して処理

++ 2-4 ポリゴン曲面
+++ ポリゴン曲面
+++ 細分割曲面
+++ 詳細度制御
++++ 簡単化
++++ 詳細度（LOD: Level of Detail）制御
+++ 平滑化処理
+++ パラメータ化
+++ 電子透かし
+++ 形状検索

++ 2-5 その他の形状生成
+++ ボクセル
++++ ボリュームデータ
+++++ ボリュームレンダリング
+++ 八分木
++++ 正方形
+++++ 四分木
++++ 立方体
+++++ 八分木
+++ メタボール
+++ 陰関数表現
++++ 放射基底関数
++++ 等値面
++++ マーキングチューブ法
+++ フラクタル
++++ 自己相似性
++++ コッホ曲線
++++ 中点変位法
@endmindmap