@startmindmap img_proc_expert_15
+ 画像からの3次元復元
-- 15-1 画像と空間の幾何学的関係
--- 15-1-1 透視投影モデルに基づく幾何学的関係の記述
--- 15-1-2 同次座標を用いた記述
--- 15-1-3 エピポーラ幾何
-- 15-2 カメラキャリブレーション
++ 15-3 ステレオビジョン
+++ 15-3-1 空間位置の計算
+++ 15-3-2 平行ステレオ
+++ 15-3-3 ステレオマッピング
+++ 15-3-4 マルチビューステレオ
++ 15-4 アクティブステレオ
++ 15-5 モーション推定と3次元復元
+++ 15-5-1 既知の空間点からのカメラ位置・姿勢の推定
+++ 15-5-2 画像対応点かららのカメラモーションと3次元位置の推定
+++ 15-5-3 大量の画像を用いた復元
@endmindmap
