@startmindmap img_proc_expert_16
+ 光学的解析とシーンの復元
-- 16-1 光学的解析
-- 16-2 放射量
--- 16-2-1 
--- 16-2-2 
-- 16-3 反射
--- 16-3-1 
--- 16-3-2 
--- 16-3-3 
-- 16-4 反射成分の分離
--- 16-4-1 
--- 16-4-2 
++ 16-5 形状の復元
+++ 16-5-1 
+++ 16-5-2 
+++ 16-5-3 
++ 16-6 反射特性の復元
+++ 16-6-1 
+++ 16-6-2 
++ 16-7 照明環境の復元
+++ 16-7-1 
+++ 16-7-2 
+++ 16-7-3 
++ 16-8 形状・反射特性・照明環境すべての復元
+++ 16-8-1 
+++ 16-8-2 
@endmindmap
