@startmindmap img_proc_basic_01
* ディジタルカメラモデル
    * 1-1 ディジタルカメラモデル
        * 撮影
            * 光 - レンズ - 撮像素子 - 情報処理 - 画像 - 調整
        * 生成
            * 被写体データ - 幾何学計算 - 光学計算 - 画像生成 - 調整
        * 画像処理
            * 3次元復元
    * 1-2 座標系とモデリング
        * 座標系
            * 2次元直交座標系
            * 3次元直交座標系
                * 右手系
                * 左手系
            * 極座標系
            * 円柱座標系
        * モデリング
            * 形状を数値で記述すること
                * 形状モデル
            * ポリゴン（多角形）
            * パラメトリック曲面
    * 1-3 幾何学的モデル
        * 2次元アフィン変換
            * 基本変換（2次元）
                * 平行移動
                * 拡大・縮小
                * 回転
                * 鏡映
                * スキュー（せん断）
        * 幾何学的変換の2つの意味
            * 1つの座標系の上で点を移動
            * 点を固定して座標系を移動
            * 移動量の符号が反転
        * 投影変換（3次元 - 2次元変換）
            * 透視投影（遠近法）
                * 投影面
                    * ウィンドウ
                    * 画角
                        * 画角 大（広角レンズ）
                        * 画角 小（望遠レンズ）
                * 消点（消失点）
                    * 1点透視
                    * 2点透視
                    * 3点透視
            * 平行投影
                * 直投影
                    * 三面図（第三角法）
                    * アイソメ図（等測投影図）
                * 斜投影
            * クリッピング
                * ビューボリューム
                    * 前方クリッピング面
                    * 後方クリッピング面
                    * 四平面
        * 1-3-5 座標系
            * モデリング座標系 
                * 形状定義
            * ワールド座標系
                * モデリング変換（モデリング座標系 → ワールド座標系）
            * カメラ座標系（アイ座標系）
                * 原点＝カメラ位置
                    * 視野変換（ワールド座標系 → カメラ座標系）
            * 投影変換
            * ウィンドウ
                * 投影面上で画像が表示される部分
            * ビューポート
                * ディスプレイ表示面のデバイス座標系（2次元）で画像が表示される部分
                    * ビューポート変換（ウィンドウ → ビューポート）
            * ビューイングパイプライン
    * 1-4 光学的モデル
        * 光と色
            * 人間の視覚
                * 角膜
                * 水晶体
                * 網膜
            * 三原色
                * 混色
                    * 加法混色（RGBカラーモデル）
                    * 減法混色（CMYカラーモデル）
            * 表色系
                * マンセル表色系
                    * 色相
                    * 明度
                    * 彩度
                    * マンセルの色立体
                * HSIカラーモデル
        * 光学的モデル
            * シェーディング
                * 平行光線
                    * 直接光
                    * 間接光
                * 拡散反射
                    * 拡散反射面
                    * 拡散反射光
            * 高度なモデル
    * 1-5 ディジタル画像
        * アナログ画像（無段階）
        * ディジタル画像
            * 標本化
            * 量子化
            * 画像座標系
            * A/D変換
            * D/A変換
        * 画像の種類
            * 2値画像
            * グレースケール画像
            * カラー画像
        * 諧調と解像度
            * 諧調（画面の明暗の調子）
            * HDR画像
        * ラスタ化（図形に対応する画素の色を描き込む処理）
            * 線分のラスタ化
                * プレゼンハムのアルゴリズム
            * ポリゴンのラスタ化
        * エイリアシングとアンチエイリアシング
            * ジャギー
            * 実際に存在しない模様
            * 標本化定理
            * フーリエ変換
                * 濃淡の変化
            * アンチエイリアシング
                * 画像処理
                    * 標本化の前、アナログ信号の段階で、短い周期の正弦波を除去する
                * CG
                    * 中間色の画素を図形の境界部分に配置する
    * 1-6 画像処理
        * 加工・出力
            * 幾何学的変換
            * 再標本化
            * 補間
                * ニアレストネイバー補間（最近隣内挿法）
                * バイリニア補間（双一次補間）
            * イメージモザイキング（画像接合）
                * 位置合わせ（座標統一）
                * 色合わせ（濃度変換）
        * 情報抽出
            * パターン認識
                * 機械学習
            * 3次元復元
                * 幾何学
                    * ステレオビジョン
                * 光学的性質
        * 伝送・蓄積
            * 圧縮
                * JPEG
    * 1-7 補足
        * カメラ
            * シャッタースピード
            * 絞り
            * 焦点距離
        * 単位
            * ビット
            * バイト
            * 接頭辞（補助単位）
                * ギガ
@endmindmap
