@startmindmap img_proc_expert_02
+ ディジタル画像の撮影
-- 2-1 ディジタルカメラの構成
-- 2-2 画像生成の幾何学的モデル
--- 2-2-1 
--- 2-2-2 
--- 2-2-3 
-- 2-3 撮影パラメータ
--- 2-3-1 
--- 2-3-2 
--- 2-3-3 
--- 2-3-4 
++ 2-4 画像のディジタル化
+++ 2-4-1 
+++ 2-4-2 
+++ 2-4-3 
+++ 2-4-4 
++ 2-5 カラー画像
+++ 2-5-1 
+++ 2-5-2 
+++ 2-5-3 
@endmindmap
