@startmindmap img_proc_expert_06
+ 周波数領域におけるフィルタリング
-- 6-1 画像のフーリエ変換
--- 6-1-1 
--- 6-1-2 
-- 6-2 周波数フィルタリング
--- 6-2-1 
--- 6-2-2 
++ 6-3 ローパスフィルタ、ハイパスフィルタ、バンドパスフィルタ
+++ 6-3-1 
+++ 6-3-2 
+++ 6-3-3 
+++ 6-3-4 
++ 6-4 高域強調フィルタ
+++ 6-4-1 
+++ 6-4-2 
@endmindmap
