@startmindmap img_proc_expert_Appendix
+ Appendix
-- a-1 画像処理の歴史
--- a-1-1 画像処理の幕開け
--- a-1-2 画像処理の工業応用
--- a-1-3 画像処理のオフィス応用
--- a-1-4 画像処理の社会応用
--- a-1-5 最近の動向
-- a-2 数学的基礎
--- a-2-1 フーリエ変換
--- a-2-2 確率
--- a-2-3 疑似逆行列
--- a-2-4 固有値と固有ベクトル
--- a-2-5 KL展開と主成分分析
-- a-3 画像入力
--- a-3-1 撮像素子の種類と特徴
--- a-3-2 高速度カメラ
--- a-3-3 リニアイメージセンサ
--- a-3-4 距離画像の取得
--- a-3-5 その他の画像の取得
++ a-4 画像出力
+++ a-4-1 ディスプレイ
+++ a-4-2 3Dディスプレイ
+++ a-4-3 プリンタ
+++ a-4-4 画像出力における画像処理
++ a-5 画像処理の特性測定
++ a-6 規格
+++ a-6-1 テレビジョンの走査方式
+++ a-6-2 映像信号接続端子
+++ a-6-3 動画像の符号化方式
+++ a-6-4 画像ファイルフォーマット
++ a-7 知的財産権
+++ a-7-1 知的財産権の概要
+++ a-7-2 著作権
+++ a-7-3 産業財産権と不正競争防止法
@endmindmap
