@startmindmap img_proc_expert_12
+ パターン認識
-- 12-1 パターン認識の基本的なアプローチ
--- 12-1-1 パターン認識の流れ
--- 12-1-2 画像からの特徴抽出
--- 12-1-3 プロトタイプ法による識別
--- 12-1-4 クラスの分布を考慮した識別
--- 12-1-5 NN法とkNN法
--- 12-1-6 kd-tree法
--- 12-1-7 ハッシングによる近似最近傍探索
--- 12-1-8 線形判別分析
--- 12-1-9 部分空間法
-- 12-2 領域学習の概要
--- 12-2-1 教師なし学習
--- 12-2-2 教師あり学習
++ 12-3 教師なし学習とクラスタリング
+++ 12-3-1 k-means法によるクラスタリング
+++ 12-3-2 主成分分析による次元圧縮
++ 12-4 教師あり学習
+++ 12-4-1 アダブースト
+++ 12-4-2 サポートベクタマシン
+++ 12-4-3 ランダムフォレスト
++ 12-5 機械学習による画像認識の応用例
+++ 12-5-1 物体検出
+++ 12-5-2 類似画像検索
+++ 12-5-3 人体姿勢推定
@endmindmap
