@startmindmap img_proc_expert_02
+ ディジタル画像の撮影
-- 2-1 ディジタルカメラの構成
-- 2-2 画像生成の幾何学的モデル
--- 2-2-1 ピンホールカメラ
--- 2-2-2 透視投影モデル
--- 2-2-3 レンズモデル
-- 2-3 撮影パラメータ
--- 2-3-1 撮影画角
--- 2-3-2 画像の明るさ
--- 2-3-3 被写界深度
--- 2-3-4 フレームレート
++ 2-4 画像のディジタル化
+++ 2-4-1 グレースケール画像
+++ 2-4-2 標本化と量子化
+++ 2-4-3 カメラ応答関数
+++ 2-4-4 時系列画像
++ 2-5 カラー画像
+++ 2-5-1 加法混色と減法混色
+++ 2-5-2 グレースケール画像とカラー画像
+++ 2-5-3 カラー画像の撮影
@endmindmap
