@startmindmap img_proc_expert_03
+ 画像の性質と色空間
-- 3-1 画像の性質を表す諸量
--- 3-1-1 
--- 3-1-2 
--- 3-1-3 
-- 3-2 人間の視覚
++ 3-3 表色系と色空間
+++ 3-3-1 
+++ 3-3-2 
+++ 3-3-3 
+++ 3-3-4 
+++ 3-3-5 
+++ 3-3-6 
+++ 3-3-7 
@endmindmap
