@startmindmap img_proc_expert_09
+ 2値画像処理
-- 9-1 2値化
--- 9-1-1 2値化の意味
--- 9-1-2 p-タイル法
--- 9-1-3 モード法
--- 9-1-4 判別分析法
-- 9-2 2値画像の基本処理と計測
--- 9-2-1 連結性
--- 9-2-2 輪郭追跡
--- 9-2-3 輪郭追跡の応用例
--- 9-2-4 収縮・膨張処理
--- 9-2-5 収縮・膨張処理の応用例
--- 9-2-6 ラベリング
--- 9-2-7 形状特徴パラメータ
--- 9-2-8 距離と距離変換画像
++ 9-3 線画像のベクトル化
+++ 9-3-1 ベクトル化処理の流れ
+++ 9-3-2 細線化手法
+++ 9-3-3 細線の特徴点抽出
+++ 9-3-4 ベクトル化
+++ 9-3-5 ベクトル化の応用例
@endmindmap
