@startmindmap img_proc_basic_01
* ディジタルカメラモデル
    * 1-1 ディジタルカメラモデル
        * 撮影
        * 生成
        * 画像処理
    * 1-2 座標系とモデリング
    * 1-3 幾何学的モデル
    * 1-4 光学的モデル
    * 1-5 ディジタル画像
    * 1-6 画像処理
    * 1-7 補足
@endmindmap
