@startmindmap img_proc_expert_04
+ 画素ごとの濃淡変換
-- 4-1 明るさ・コントラストの変換
--- 4-1-1 トーンカーブ
--- 4-1-2 折れ線型トーンカーブによる変換
--- 4-1-3 累乗型トーンカーブによる変換（ガンマ変換）
--- 4-1-4 S字型トーンカーブによる変換
--- 4-1-5 ヒストグラム平坦化
-- 4-2 特殊な効果
--- 4-2-1 濃淡の反転
--- 4-2-2 ポスタリゼーションと2値化
--- 4-2-3 ソラリゼーション
++ 4-3 カラー画像の変換
+++ 4-3-1 R、G、Bトーンカーブによる変換
+++ 4-3-2 疑似カラー
+++ 4-3-3 色相・彩度・明度の変化
+++ 4-3-4 色補正
++ 4-4 複数の画像の利用
+++ 4-4-1 画像間演算
+++ 4-4-2 マスク処理
@endmindmap
