@startmindmap img_proc_expert_08
+ 幾何学的変換
-- 8-1 線形変換
--- 8-1-1 線形変換の一般形
--- 8-1-2 拡大・縮小
--- 8-1-3 回転
--- 8-1-4 鏡映
--- 8-1-5 スキュー
--- 8-1-6 合成変換
-- 8-2 同時変換とアフィン変換・射影変換
--- 8-2-1 平行移動
--- 8-2-2 同次座標
--- 8-2-3 アフィン変換
--- 8-2-4 射影変換
--- 8-2-5 合成変換
++ 8-3 画像の再標本化と補間
+++ 8-3-1 画像の再標本化
+++ 8-3-2 ニアレストネイバー
+++ 8-3-3 バイリニア補間
+++ 8-3-4 バイキュービック補間
++ 8-4 イメージモザイキング
+++ 8-4-1 イメージモザイキングとその概略処理手順
+++ 8-4-2 特徴点の抽出とマッチング
+++ 8-4-3 幾何学的変換の推定
+++ 8-4-4 画像の幾何学的変換と合成
+++ 8-4-5 平面パノラマ、円筒面パノラマ、球面パノラマ
@endmindmap
