@startmindmap img_proc_expert_13
+ 深層学習による画像認識と生成
-- 13-1 ニューラルネットワーク
--- 13-1-1 単純パーセプトロン
--- 13-1-2 誤差逆伝播法によるニューラルネットワークの学習
-- 13-2 深層学習
--- 13-2-1 たたみ込みニューラルネットワーク（CNN）
--- 13-2-2 汎化能力の向上
++ 13-3 CNNによる画像認識と画像生成
+++ 13-3-1 CNNによる画像認識
+++ 13-3-2 画像分類
+++ 13-3-3 物体検出
+++ 13-3-4 セマンティックセグメンテーション
+++ 13-3-5 姿勢推定
+++ 13-3-6 GAN
@endmindmap
