@startmindmap img_proc_expert_04
+ 画素ごとの濃淡変換
-- 4-1 明るさ・コントラストの変換
--- 4-1-1 
--- 4-1-2 
--- 4-1-3 
--- 4-1-4 
--- 4-1-5 
-- 4-2 特殊な効果
--- 4-2-1 
--- 4-2-2 
--- 4-2-3 
++ 4-3 カラー画像の変換
+++ 4-3-1 
+++ 4-3-2 
+++ 4-3-3 
+++ 4-3-4 
++ 4-4 複数の画像の利用
+++ 4-4-1 
+++ 4-4-2 
@endmindmap
