@startmindmap img_proc_basic_07
+ パターン・特徴の検出とパターン認識
-- 7-1 特異点による画像間のマッチング
--- 7-1-1 特徴点による2つの画像の対応付け
--- 7-1-2 特徴点検出
--- 7-1-3 スケールと回転に不変な特徴量
--- 7-1-4 対応点探索
-- 7-2 図形の検出
--- 7-2-1 直線の検出
--- 7-2-2 円の検出
++ 7-3 パターンの検出
+++ 7-3-1 テンプレートマッチング
+++ 7-3-2 相違度の計算
++ 7-4 パターン認識
+++ 7-4-1 パターン認識の流れ
+++ 7-4-2 画素からの特徴抽出
+++ 7-4-3 プロトタイプ法による識別
+++ 7-4-4 教師あり学習
+++ 7-4-5 教師あり2クラス識別
+++ 7-4-6 教師あり多クラス識別
++ 7-5 ニューラルネットワークと深層学習
+++ 7-5-1 ニューラルネットワーク
+++ 7-5-2 深層学習とたたみ込みネットワーク
@endmindmap
