@startmindmap img_proc_expert_05
+ 領域に基づく濃淡変換（領域フィルタリング）
-- 5-1 空間フィルタリング
-- 5-2 平滑化
--- 5-2-1 
--- 5-2-2 
--- 5-2-3 
-- 5-3 エッジ検出
--- 5-3-1 
--- 5-3-2 
--- 5-3-3 
--- 5-3-4 
++ 5-4 鮮鋭化
++ 5-5 エッジを保存した平滑化
+++ 5-5-1 
+++ 5-5-2 
+++ 5-5-3 
+++ 5-5-4 
+++ 5-5-5 
@endmindmap
